FROM python:3.10.12

WORKDIR /app

COPY . /app

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install \
    nginx \
    python3-dev \
    sqlite3\
    build-essential

COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt --src /usr/local/src

EXPOSE 5000

CMD ["python", "./src/flask_api.py"]
